# Change these first
owner: Healthlane-Technologies # Your GitHub organization or username, where this repository lives
repo: zelcloud-uptime # The name of this repository

sites:
  - name: Zelthy Cloud
    url: https://www.zelthy.com/
  - name: PSPhere Cloud
    url: https://psphere.app

status-website:
  baseUrl: /zelcloud-uptime
  logoUrl: https://zelthy-initium-production-static.s3.amazonaws.com/static/zelthymain/images/og-image.jpeg
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


