# Change these first
owner: Zelthy # Your GitHub organization or username, where this repository lives
repo: zelcloud-uptime # The name of this repository

sites:
  - name: Zelthy Cloud
    url: https://cloud1.zelthy.com
  - name: PSPhere Cloud
    url: https://psphere.app

status-website:
  baseUrl: /zelcloud-uptime # where "repo" is your repository name
  name: Zelthy Cloud Uptime Status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
